/*
 * v4
 *
 * The bol.com API for Retailers.
 *
 * API version: 4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// CustomerDetails struct for CustomerDetails
type CustomerDetails struct {
	// The salutation code.
	SalutationCode string `json:"salutationCode,omitempty"`
	// The first name.
	FirstName string `json:"firstName,omitempty"`
	// The surname.
	Surname string `json:"surname,omitempty"`
	// The street name.
	StreetName string `json:"streetName,omitempty"`
	// The house number.
	HouseNumber string `json:"houseNumber,omitempty"`
	// The extension on the house number.
	HouseNumberExtended string `json:"houseNumberExtended,omitempty"`
	// The address supplement.
	AddressSupplement string `json:"addressSupplement,omitempty"`
	// Extra information about the address.
	ExtraAddressInformation string `json:"extraAddressInformation,omitempty"`
	// The ZIP code.
	ZipCode string `json:"zipCode,omitempty"`
	// The name of the city.
	City string `json:"city,omitempty"`
	// The country code.
	CountryCode string `json:"countryCode,omitempty"`
	// The e-mail address.
	Email string `json:"email,omitempty"`
	// The delivery phone number.
	DeliveryPhoneNumber string `json:"deliveryPhoneNumber,omitempty"`
	// The company name.
	Company string `json:"company,omitempty"`
	// The VAT number.
	VatNumber string `json:"vatNumber,omitempty"`
}
