/*
 * v4
 *
 * The bol.com API for Retailers.
 *
 * API version: 4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// Link struct for Link
type Link struct {
	Rel string `json:"rel,omitempty"`
	Href string `json:"href,omitempty"`
	// HTTP method
	Method string `json:"method,omitempty"`
}
