/*
 * v4
 *
 * The bol.com API for Retailers.
 *
 * API version: 4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// PeriodResponse struct for PeriodResponse
type PeriodResponse struct {
	// The number of weeks into the future, starting from today.
	WeeksAhead int32 `json:"weeksAhead,omitempty"`
	Total TotalResponse `json:"total"`
	Countries []CountryTotalResponse `json:"countries"`
}
