/*
 * v4
 *
 * The bol.com API for Retailers.
 *
 * API version: 4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// CreateUnpublishedOfferReportRequest struct for CreateUnpublishedOfferReportRequest
type CreateUnpublishedOfferReportRequest struct {
	// The file format in which to return the export.
	Format string `json:"format"`
}
