/*
 * v4
 *
 * The bol.com API for Retailers.
 *
 * API version: 4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// Violation Describes a violation that occurred interacting with the API.
type Violation struct {
	// Describes the origin of the error, for instance a field or query parameter validation error.
	Name string `json:"name,omitempty"`
	// Detailed description of the validation error that caused the problem.
	Reason string `json:"reason,omitempty"`
}
