/*
 * v4
 *
 * The bol.com API for Retailers.
 *
 * API version: 4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// RejectedAttributeResponse An rejected attribute.
type RejectedAttributeResponse struct {
	// Identifier of the attribute from the data model.
	AttributeId string `json:"attributeId,omitempty"`
	RejectionErrors []RejectionError `json:"rejectionErrors"`
}
