/*
 * v4
 *
 * The bol.com API for Retailers.
 *
 * API version: 4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// Attribute struct for Attribute
type Attribute struct {
	// Identifier of the attribute from the data model.
	Id string `json:"id"`
	// A list of attribute values.
	Values []AttributeValue `json:"values"`
}
