/*
 * v4
 *
 * The bol.com API for Retailers.
 *
 * API version: 4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// ReturnRequest struct for ReturnRequest
type ReturnRequest struct {
	HandlingResult string `json:"handlingResult,omitempty"`
	QuantityReturned int32 `json:"quantityReturned"`
}
