/*
 * v4
 *
 * The bol.com API for Retailers.
 *
 * API version: 4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// AttributeValue struct for AttributeValue
type AttributeValue struct {
	// The value(s) of the attribute.
	Value string `json:"value"`
	// The unit identifier of the attribute.
	UnitId string `json:"unitId,omitempty"`
}
