/*
 * v4
 *
 * The bol.com API for Retailers.
 *
 * API version: 4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// SubscriptionResponse struct for SubscriptionResponse
type SubscriptionResponse struct {
	// A unique identifier for the subscription
	Id int64 `json:"id"`
	// Type of event
	Resources []string `json:"resources"`
	// URL to receive this WebHook notification
	Url string `json:"url"`
}
