/*
 * v4
 *
 * The bol.com API for Retailers.
 *
 * API version: 4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// OfferInsights Offer insights.
type OfferInsights struct {
	OfferInsights []OfferInsight `json:"offerInsights"`
}
