/*
 * v4
 *
 * The bol.com API for Retailers.
 *
 * API version: 4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// Problem Describes a problem that occurred interacting with the API.
type Problem struct {
	// Type URI for this problem. Fixed value: https://api.bol.com/problems.
	Type string `json:"type,omitempty"`
	// Title describing the nature of the problem.
	Title string `json:"title,omitempty"`
	// HTTP status returned from the endpoint causing the problem.
	Status int32 `json:"status,omitempty"`
	// Detailed error message describing in additional detail what caused the service to return this problem.
	Detail string `json:"detail,omitempty"`
	// Host identifier describing the server instance that reported the problem.
	Host string `json:"host,omitempty"`
	// Full URI path of the resource that reported the problem.
	Instance string `json:"instance,omitempty"`
	Violations []Violation `json:"violations,omitempty"`
}
