/*
 * v4
 *
 * The bol.com API for Retailers.
 *
 * API version: 4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// OrderItem struct for OrderItem
type OrderItem struct {
	// The id for the order item (1 order can have multiple order items).
	OrderItemId string `json:"orderItemId"`
}
