/*
 * v4
 *
 * The bol.com API for Retailers.
 *
 * API version: 4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// PackageRestrictions struct for PackageRestrictions
type PackageRestrictions struct {
	// The weight of a package.
	MaxWeight string `json:"maxWeight,omitempty"`
	// The dimensions of a package.
	MaxDimensions string `json:"maxDimensions,omitempty"`
}
