/*
 * v4
 *
 * The bol.com API for Retailers.
 *
 * API version: 4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// BulkProcessStatusRequest struct for BulkProcessStatusRequest
type BulkProcessStatusRequest struct {
	ProcessStatusQueries []ProcessStatusId `json:"processStatusQueries"`
}
