/*
 * v4
 *
 * The bol.com API for Retailers.
 *
 * API version: 4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CreateSubscriptionRequest struct for CreateSubscriptionRequest
type CreateSubscriptionRequest struct {
	// Type of event
	Resources []string `json:"resources"`
	// URL to receive this WebHook notification
	Url string `json:"url"`
}
