/*
 * v4
 *
 * The bol.com API for Retailers.
 *
 * API version: 4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Period struct for Period
type Period struct {
	// Day of the month.
	Day int32 `json:"day,omitempty"`
	// Week of the year.
	Week int32 `json:"week,omitempty"`
	// Month of the year.
	Month int32 `json:"month,omitempty"`
	// Year
	Year int32 `json:"year,omitempty"`
}
