/*
 * v4
 *
 * The bol.com API for Retailers.
 *
 * API version: 4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ProcessStatusId struct for ProcessStatusId
type ProcessStatusId struct {
	// The process status id.
	Id int64 `json:"id,omitempty"`
}
