/*
 * v4
 *
 * The bol.com API for Retailers.
 *
 * API version: 4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// SubscriptionsResponse struct for SubscriptionsResponse
type SubscriptionsResponse struct {
	Subscriptions []SubscriptionResponse `json:"subscriptions"`
}
