/*
 * v4
 *
 * The bol.com API for Retailers.
 *
 * API version: 4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// RejectionError struct for RejectionError
type RejectionError struct {
	// The rejection error code.
	Code int32 `json:"code,omitempty"`
	// The rejection error message explains why the value was rejected.
	Message string `json:"message,omitempty"`
}
