/*
 * v4
 *
 * The bol.com API for Retailers.
 *
 * API version: 4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// LabelPrice struct for LabelPrice
type LabelPrice struct {
	// The price that is charged for this delivery option, excluding VAT.
	TotalPrice float32 `json:"totalPrice,omitempty"`
}
