/*
 * v4
 *
 * The bol.com API for Retailers.
 *
 * API version: 4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ProductContentResponse An rejected product content.
type ProductContentResponse struct {
	// A user defined unique reference to identify the products in the upload.
	InternalReference string `json:"internalReference,omitempty"`
	RejectedAttributes []RejectedAttributeResponse `json:"rejectedAttributes,omitempty"`
	// The end status of the rejected attribute.
	Status string `json:"status,omitempty"`
	// The rejection error code.
	ErrorCode int32 `json:"errorCode,omitempty"`
	// The rejection error message explains why the value was rejected.
	ErrorDescription string `json:"errorDescription,omitempty"`
}
