/*
 * v4
 *
 * The bol.com API for Retailers.
 *
 * API version: 4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// DeliveryOptionsRequest The configuration of order items to get delivery options for.
type DeliveryOptionsRequest struct {
	// Order items for which the delivery options are requested.
	OrderItems []OrderItem `json:"orderItems"`
}
