/*
 * v4
 *
 * The bol.com API for Retailers.
 *
 * API version: 4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// RetailPrice Retail price information with the country in which it applies.
type RetailPrice struct {
	// The retail price for this product with two decimals precision. The price includes VAT.
	Price float32 `json:"price"`
	// The ISO-3166 country code. 
	Country string `json:"country"`
}
