/*
 * v4
 *
 * The bol.com API for Retailers.
 *
 * API version: 4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// DeliveryOptionsResponse The possible delivery options based on a shippable configuration
type DeliveryOptionsResponse struct {
	DeliveryOptions []DeliveryOption `json:"deliveryOptions"`
}
