/*
 * v4
 *
 * The bol.com API for Retailers.
 *
 * API version: 4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// Return struct for Return
type Return struct {
	// Unique identifier for a return.
	ReturnId int64 `json:"returnId,omitempty"`
	// The date and time in ISO 8601 format when this return was registered.
	RegistrationDateTime time.Time `json:"registrationDateTime,omitempty"`
	// Specifies whether this shipment has been fulfilled by the retailer (FBR) or fulfilled by bol.com (FBB). Defaults to FBR.
	FulfilmentMethod string `json:"fulfilmentMethod,omitempty"`
	ReturnItems []ReturnItem `json:"returnItems"`
}
