/*
 * v4
 *
 * The bol.com API for Retailers.
 *
 * API version: 4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ReturnItem struct for ReturnItem
type ReturnItem struct {
	// The RMA (Return Merchandise Authorization) id that identifies this particular return.
	RmaId int64 `json:"rmaId,omitempty"`
	// The id of the customer order this return item is in.
	OrderId string `json:"orderId,omitempty"`
	// The EAN number associated with this product.
	Ean string `json:"ean,omitempty"`
	// The product title.
	Title string `json:"title,omitempty"`
	// The quantity that is expected to be returned by the customer. Note: this can be greater than 1 in case the customer ordered a quantity greater than 1 of the same product in the same customer order.
	ExpectedQuantity int32 `json:"expectedQuantity,omitempty"`
	// The reason why the customer returned this product.
	ReturnReason string `json:"returnReason,omitempty"`
	// Additional details from the customer as to why this item was returned.
	ReturnReasonComments string `json:"returnReasonComments,omitempty"`
	// The track and trace code that is associated with this transport.
	TrackAndTrace string `json:"trackAndTrace,omitempty"`
	// The name of the transporter.
	TransporterName string `json:"transporterName,omitempty"`
	// Indicates if this return item has been handled (by the retailer).
	Handled bool `json:"handled,omitempty"`
	ProcessingResults []ReturnProcessingResult `json:"processingResults"`
	CustomerDetails CustomerDetails `json:"customerDetails,omitempty"`
}
