/*
 * v4
 *
 * The bol.com API for Retailers.
 *
 * API version: 4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ProcessStatusResponse struct for ProcessStatusResponse
type ProcessStatusResponse struct {
	ProcessStatuses []ProcessStatus `json:"processStatuses"`
}
