/*
 * v4
 *
 * The bol.com API for Retailers.
 *
 * API version: 4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ReturnsResponse struct for ReturnsResponse
type ReturnsResponse struct {
	Returns []ReducedReturn `json:"returns"`
}
