/*
 * v4
 *
 * The bol.com API for Retailers.
 *
 * API version: 4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// TransportInstruction struct for TransportInstruction
type TransportInstruction struct {
	// Specify the transporter that will carry out the shipment.
	TransporterCode string `json:"transporterCode,omitempty"`
	// The track and trace code that is associated with this transport.
	TrackAndTrace string `json:"trackAndTrace,omitempty"`
}
