/*
 * v4
 *
 * The bol.com API for Retailers.
 *
 * API version: 4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// RetailPriceResponse Retail price information for products and the countries in which they apply.
type RetailPriceResponse struct {
	RetailPrices []RetailPrice `json:"retailPrices"`
}
