/*
 * v4
 *
 * The bol.com API for Retailers.
 *
 * API version: 4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Country struct for Country
type Country struct {
	// The country code.
	CountryCode string `json:"countryCode,omitempty"`
	// The total value of offer insight.
	Value float64 `json:"value,omitempty"`
}
