/*
 * v4
 *
 * The bol.com API for Retailers.
 *
 * API version: 4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CreateProductContentRequest struct for CreateProductContentRequest
type CreateProductContentRequest struct {
	// The language to indicate the language of the supplied content.
	Language string `json:"language"`
	// A list of supplied products and their attributes. Attributes that are required for publishing products online will be mentioned in the data model.
	ProductContents []ProductContent `json:"productContents"`
}
