/*
 * v4
 *
 * The bol.com API for Retailers.
 *
 * API version: 4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CountryTotalResponse struct for CountryTotalResponse
type CountryTotalResponse struct {
	// The country code.
	CountryCode string `json:"countryCode,omitempty"`
	// Minimum number of estimated sales expectations on the bol.com platform.
	Minimum float64 `json:"minimum,omitempty"`
	// Maximum number of estimated sales expectations on the bol.com platform.
	Maximum float64 `json:"maximum,omitempty"`
}
